# Site settings

title: Guowei Lv

email: lvguowei1002@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Welcome to Guowei's home page, grab a drink and enjoy your stay!

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://lvguowei.github.io"

# twitter_username: jekyllrb

github_username: lvguowei

# Build settings
markdown: kramdown

excerpt_separator: ""